// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR3AO1gBVhJp2kViAnsFlvmGhZ4OxAm80',
    appId: '1:989718417949:web:946235eed95250dfdfacf4',
    messagingSenderId: '989718417949',
    projectId: 'cinebyte-network',
    authDomain: 'cinebyte-network.firebaseapp.com',
    storageBucket: 'cinebyte-network.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJOpodYkxyLw0FjVt1KM81aAPOAx-jN1U',
    appId: '1:989718417949:ios:71d4f3068d252351dfacf4',
    messagingSenderId: '989718417949',
    projectId: 'cinebyte-network',
    storageBucket: 'cinebyte-network.appspot.com',
    iosBundleId: 'com.example.cinebyteAdminWebapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR3AO1gBVhJp2kViAnsFlvmGhZ4OxAm80',
    appId: '1:989718417949:web:dd608cebea5597bcdfacf4',
    messagingSenderId: '989718417949',
    projectId: 'cinebyte-network',
    authDomain: 'cinebyte-network.firebaseapp.com',
    storageBucket: 'cinebyte-network.appspot.com',
  );
}
